In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

In [ ]:
!gdown 1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1
!gdown 1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR
!gdown 1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h

Downloading...
From: https://drive.google.com/uc?id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1
To: /content/movies.csv
100% 516k/516k [00:00<00:00, 66.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR
To: /content/ratings.csv
100% 2.48M/2.48M [00:00<00:00, 163MB/s]
Downloading...
From: https://drive.google.com/uc?id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h
To: /content/users.csv
100% 16.8k/16.8k [00:00<00:00, 35.2MB/s]


In [ ]:
# Loading Data
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [ ]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [ ]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller

In [ ]:
ratings.head()

userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
movies.shape

(1000, 3)

In [ ]:
ratings.shape

(63250, 4)

In [ ]:
rm = ratings.pivot(index = 'userId', columns ='movieId', values = 'rating').fillna(0)
rm.head()

movieId  1       2       3       5       6       7       10      11      \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           5.0     0.0     2.0     3.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     3.0     0.0     3.0     0.0     4.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  16      17      ...  88125   89745   91529   96610   99114   109374  \
userId                   ...                                                   
1           4.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     5.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  109487  111759  112852  116797  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 1000 columns]

In [ ]:
rm.shape

(668, 1000)

In [ ]:
(rm > 0).sum().sum() / (rm.shape[0] * rm.shape[1])

0.09468562874251497

In [ ]:
rm_small = rm.copy()
rm_small = rm_small[rm_small.columns[:100]]
rm_small = rm_small.head(100)

In [ ]:
rm_small.shape

(100, 100)

In [ ]:
rm_small

movieId  1    2    3    5    6    7    10   11   16   17   ...  300  303  306  \
userId                                                     ...                  
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...  0.0  0.0  0.0   
2        5.0  0.0  2.0  3.0  0.0  0.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
3        0.0  0.0  0.0  3.0  0.0  3.0  0.0  4.0  0.0  0.0  ...  4.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  5.0   
5        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
96       5.0  0.0  4.0  3.0  4.0  3.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
97       3.5  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
98       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
99       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
100      3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

movieId  307  308  315  316  317  318  319  
userId                                      
1        0.0  0.0  0.0  0.0  0.0  4.0  0.0  
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4        5.0  5.0  0.0  0.0  0.0  4.0  0.0  
5        0.0  0.0  0.0  0.0  0.0  0.0  1.0  
...      ...  ...  ...  ...  ...  ...  ...  
96       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
97       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
98       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
99       0.0  0.0  0.0  0.0  0.0  3.0  0.0  
100      0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[100 rows x 100 columns]

In [ ]:
K = 2
P = np.random.normal(size=(rm_small.shape[0], K))
Q = np.random.normal(size=(rm_small.shape[1], K))


def matrix_factorization(R, P, Q, K, steps=100, alpha=0.01):
    Q = Q.T
    # P : (n,k)
    # Q : (k,m)
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] == 0:
                    continue
                eij = np.dot(P[i,:],Q[:,j]) - R[i][j]

                for k in range(K):
                    P[i][k] = P[i][k] - alpha * (2 * eij * Q[k][j])
                    Q[k][j] = Q[k][j] - alpha * (2 * eij * P[i][k])
    return P, Q.T

In [ ]:
P_, Q_ =  matrix_factorization(rm_small.values.copy(), P.copy(), Q.copy(), 2)

In [ ]:
P_[:5]

array([[-1.37592694, -0.27471949],
       [-1.6178631 , -0.860858  ],
       [-1.8625427 ,  0.12560585],
       [-1.81066761,  0.06333299],
       [-0.84593194,  0.15790227]])

In [ ]:
Q_[:10]

array([[-2.38832722, -0.49833106],
       [-2.04448405,  1.24316061],
       [-1.82435125,  0.34160095],
       [-1.67274581, -1.13616701],
       [-2.38371372,  0.2270551 ],
       [-1.61466472,  0.69960501],
       [-2.24186153, -0.4295574 ],
       [-2.0070255 ,  1.05697068],
       [-2.41228293, -2.47838614],
       [-2.32206347, -1.28990901]])

In [ ]:
# u4, 17
np.dot(P_[3], Q_[17])

4.683872091655198

In [ ]:
# predicted rating clipped to [0, 5]
np.clip(np.dot(P_[3], Q_[17]), 0, 5)

4.683872091655198

In [ ]:
# actual rating
rm_small.values[3, 17]

5.0

In [ ]:
# predicted vs actual rating.
print(np.clip(np.dot(P_[4], Q_[36]), 0, 5,),  rm_small.values[4, 36])

1.575083010051826 0.5


In [ ]:
from sklearn.metrics import mean_squared_error as mse

rm_ = np.dot(P_, Q_.T)

In [ ]:
mse( rm_small.values[rm_small>0] , rm_[rm_small>0] )**0.5

0.6816672768779493

In [ ]:
# on an average the predict ratings are 0.6 units away from acutal

# CMFREC

In [ ]:
!pip install cmfrec

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.3/268.3 kB 8.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached findblas-0.1.26.post1-py3-none-any.whl
  Created wheel for cmfrec: filename=cmfrec-3.5.1.post10-cp310-cp310-linux_x86_64.whl size=5669626 sha256=7460b0ae17ff832a49ea5c47d11a89f412b5be083465071cffc1be25931d9050
  Stored in directory: /root/.cache/pip/wheels/cc/80/d7/9b7d9361970eb499c0227a3fac504240f7793dec0d9793bee6
Successfully built cmfrec


In [ ]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names
rm_raw.head()

UserId  ItemId  Rating
0       1      16     4.0
1       1      24     1.5
2       1      32     4.0
3       1      47     4.0
4       1      50     4.0

In [ ]:
ratings.head()

userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
from cmfrec import CMF

In [ ]:
model = CMF(k = 2, lambda_ = 0.1, verbose = False, user_bias= False, item_bias=False)
model.fit(rm_raw)

Collective matrix factorization model
(explicit-feedback variant)


In [ ]:
model.A_.shape

(668, 2)

In [ ]:
model.B_.shape

(1000, 2)

In [ ]:
ratings['rating'].mean()

3.6659130434782607

In [ ]:
model.glob_mean_ # (mu)

3.6659131050109863

In [ ]:
# RMSE
rm__ = np.dot(model.A_, model.B_.T) + model.glob_mean_

mse( rm.values[rm>0] , rm__[rm>0] )**0.5

1.0629517113958387

In [ ]:
top_items = model.topN(user = 1, n = 10)
top_items

array([ 44555,   7502,   1217,   1172,    923,    318,   1212,    922,
       109374,   5971])

In [ ]:
movies.loc[movies.movieId.isin(top_items)]

movieId                                              title  \
279       318                   Shawshank Redemption, The (1994)   
743       922      Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)   
744       923                                Citizen Kane (1941)   
938      1172     Cinema Paradiso (Nuovo cinema Paradiso) (1989)   
973      1212                              Third Man, The (1949)   
978      1217                                         Ran (1985)   
4472     5971       My Neighbor Totoro (Tonari no Totoro) (1988)   
5390     7502                            Band of Brothers (2001)   
6958    44555  Lives of Others, The (Das leben der Anderen) (...   
9908   109374                   Grand Budapest Hotel, The (2014)   

                                genres  
279                        Crime|Drama  
743            Drama|Film-Noir|Romance  
744                      Drama|Mystery  
938                              Drama  
973         Film-Noir|Mystery|Thriller  
978                          Drama|War  
4472  Animation|Children|Drama|Fantasy  
5390                  Action|Drama|War  
6958            Drama|Romance|Thriller  
9908                      Comedy|Drama